services:

  # MariaDB
  mariadb:
    image: mariadb:12.2.2-noble
    environment:
      #MARIADB_RANDOM_ROOT_PASSWORD: "true"
      MARIADB_DATABASE: default_database
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mariadb-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"

  # connect to database mariadb with proper user/pass and default_database
  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8080"

  mongo:
    image: mongo:8.2.5
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminUser
      MONGO_INITDB_ROOT_PASSWORD: passwordUser
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mondo-data:/data/db

  mongo-express:
    image: mongo-express:1.0.2-20
    restart: always
    ports:
      - "9000:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://adminUser:passwordUser@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: "true"
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass