/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package poc.kotlin.app


fun main()  {
    processAsync()
    println("Main finished")
}


fun processAsync(){
    println("Delay finieshed")
}









