logging:
  level:
    root: INFO
    kisonar.poc.kotlin.app.service: DEBUG

spring:
  cloud:
    config:
      enabled: false
  main:
    banner-mode: console

  application:
    name: kisonar-poc-kotlin-spring-boot

  mongodb:
    uri: mongodb://adminUser:passwordUser@localhost:27017/hiven?authSource=admin&authMechanism=SCRAM-SHA-1
  data:
    mongodb:
      auto-index-creation: true


  management:
    info:
      java:
        enabled: true
    endpoints:
      web:
        exposure:
          include: health, info
  jackson:
    default-property-inclusion: always
    constructor-detector: use_properties_based

app.config:
  httpclient:
    max-idle-time: PT20S
    max-life-time: PT60S
    eviction-interval: PT120S