/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    //id("poc.kotlin.kotlin-application-conventions")
    id("application")
    //id("myproject.java-conventions")
}

dependencies {
    //implementation("org.apache.commons:commons-text")
    //implementation(project(":service"))
    //implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4")
}

application {
    // Define the main class for the application.
    mainClass.set("poc.kotlin.app.AppKt")
}
